id: P010700
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-20 10:20:32.210661
source_metadata:
  id: bdr:W30490
  title: འཇང་གླིང་གཡུལ་འགྱེད།
  author: ''
  volumes:
    5169a49d6ada4199a9df3d3cffea055d:
      image_group_id: I1KG17263
      title: ''
      volume_number: 1
      total_pages: 356
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
