id: P010700
initial_creation_type: ocr
source_metadata:
  id: bdr:W30490
  title: འཇང་གླིང་གཡུལ་འགྱེད།
  author: ''
  volumes:
    5169a49d6ada4199a9df3d3cffea055d:
      image_group_id: I1KG17263
      title: ''
      volume_number: 1
      total_pages: 356
